name: AllergyLab CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build images
      run: |
        cd Part7a
        docker build -t ${{ secrets.DOCKER_USERNAME }}/al-app:latest ./app
        docker build -t ${{ secrets.DOCKER_USERNAME }}/al-db-loader:latest ./db-loader
        docker build -t ${{ secrets.DOCKER_USERNAME }}/al-email:latest ./email
