name: AllergyLab CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Build images
      run: |
        cd Part7a
        docker build -t ${{ secrets.DOCKER_USERNAME }}/al-app:latest ./app
        docker build -t ${{ secrets.DOCKER_USERNAME }}/al-db-loader:latest ./db-loader
        docker build -t ${{ secrets.DOCKER_USERNAME }}/al-email:latest ./email
    - name: Log in to Docker
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Push images to DockerHub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/al-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/al-db-loader:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/al-email:latest
